language: node_js
sudo: required
node_js:
  - 5.3
env:
  - PATH=$HOME/purescript:$PATH
install:
- TAG="v0.8.0"
- wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
- tar -xvf $HOME/purescript.tar.gz -C $HOME/
- chmod a+x $HOME/purescript
- npm install bower pulp -g
- bower install
# Installing stack for build script
- wget -O $HOME/stack.tar.gz https://www.stackage.org/stack/linux-x86_64
- mkdir $HOME/stack
- tar -xvf $HOME/stack.tar.gz -C $HOME/stack/
- chmod a+x $HOME/stack/stack

before_script:
- export PATH=$PATH:$HOME/stack/
- chmod a+x test/Main.hs
script:
  - pulp build
  - ./test/Main.hs & sleep 3 && pulp test 
