language: node_js
sudo: required
node_js:
  - 5.3
env:
  - PATH=$HOME/purescript:$PATH
install:
- TAG="v0.8.0"
- wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
- tar -xvf $HOME/purescript.tar.gz -C $HOME/
- chmod a+x $HOME/purescript
- npm install bower pulp browserify -g
- npm install xhr2
- bower install
# Installing stack for build script
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442
- echo 'deb http://download.fpcomplete.com/ubuntu precise main'| sudo tee /etc/apt/sources.list.d/fpco.list
- sudo apt-get update && sudo apt-get install stack -y
- stack setup --resolver lts-5.1
- stack build --resolver lts-5.1 yesod yesod-auth wai-cors wai-middleware-static

before_script:
- chmod a+x test/Main.hs
- ./test/Main.hs &
- sleep 10

script:
- pulp build
- pulp test -r browserify > output/test.js
- phantomjs phantom.js
- sleep 10

cache:
  directories:
    - $HOME/.stack
